### ISSUE TITLE
Use bcrypt 0.8.x

### ISSUE THREAD

**Issue by der-On** [geddy/geddy-passport#27]
Bcrypt 0.7.x has major compilation problems on various platforms

**Comment by dlabey** [comment]
Hi I am experiencing a build issue because of this

**Comment by der-On** [comment]
@dlabey: because of bcrypt 0.7 or 0.8?

**Comment by dlabey** [comment]
bcrypt 0.7. I think it's because of the newer version of Node too

**Comment by dlabey** [comment]
Is this project dead? I was trying to install this and I am on an Mac OSX with the latest version of stable node (homebrew) from a fresh Geddy installationl

**Comment by der-On** [comment]
@mde How about giving more people npm publish access to geddy and it's (sub-) modules? I would actually try to investigate on this, but am not able to publish anything geddy related on npm (but the generators)

**Comment by mde** [comment]
@der-On Yes, I will do this tomorrow! Excellent idea.

**Comment by mde** [comment]
I've now added owner access to some people: @der-On, @ben-ng, @phanect, @flyswatter. If more people want push access, let me know. Sorry this took so long to happen.

**Comment by der-On** [comment]
Merged, tested and published in v0.1.8

Have fun!
